---
abstract: Insert fixtures into your Jifty application database
author:
- shelling <shelling@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.007
license: mit
name: JiftyX-Fixtures
requires:
  Getopt::Compact: '0'
  Jifty: '0'
  Text::Greeking: '0'
  YAML: '0'
version: '0.02'
